name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - backend
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.check-env-url.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build (if applicable)
        run: npm run build --if-present

      - name: Test (if applicable)
        run: npm run test --if-present

      - name: Package application
        run: |
          zip -r app.zip . -x "*.git*"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to Elastic Beanstalk
        id: deploy-to-beanstalk
        run: |
          # Generate a unique version label by appending the current timestamp to $GITHUB_SHA
          VERSION_LABEL="$GITHUB_SHA-$(date +%s)"
          
          # Upload the app.zip to S3 with the unique version label
          aws s3 cp app.zip s3://elasticbeanstalk-ap-south-1-940420095386/app-$VERSION_LABEL.zip
          
          # Create a new application version with the unique version label
          aws elasticbeanstalk create-application-version \
            --application-name pitch-backend \
            --version-label $VERSION_LABEL \
            --source-bundle S3Bucket="elasticbeanstalk-ap-south-1-940420095386",S3Key="app-$VERSION_LABEL.zip"
          
          # Update the environment with the new version label
          aws elasticbeanstalk update-environment \
            --environment-name Pitch-backend-env \
            --version-label $VERSION_LABEL
        env:
          AWS_REGION: ap-south-1

      - name: Check Environment URL
        id: check-env-url
        run: |
          echo "webapp-url=https://Pitch-backend-env.eba-4n4stnmn.ap-south-1.elasticbeanstalk.com" >> $GITHUB_OUTPUT
#PUSH CHANGE1